name: 'Slacker'
description: 'Notify and update slack notifications'
inputs:
  channel-id:
    description: 'Slack channel id'
    required: true
  text:
    description: 'E.g. build status'
    required: true
  short-text:
    description: 'The text that appears in the notification'
    required: false
  args:
    type: 'string'
    description: |
      'A list of values to inject into the text'
    required: false
  message-id:
    description: 'Id of the existing message to update'
    required: false
  reply-to-id:
    description: 'Id of the existing message to reply to'
    required: false
  debug:
    type: 'boolean'
    required: false
    default: false
  bot-name:
    type: 'string'
    description: 'The bot name to be displayed as sender'
    required: false
  bot-icon:
    type: 'string'
    description: 'The bot icon to be displayed'
    required: false
outputs:
  message-id:
    description: 'The id of the message sent'
runs:
  using: 'node20'
  main: 'dist/index.js'
